// Shared domain core — single source of truth (mock).
// Loads all data/*.json once; pages read via the accessors below.

import { fetchJSON } from './fetch-json.js';

const DATA = Object.create(null);
const hasOwn = (object, key) => Object.prototype.hasOwnProperty.call(object, key);
const isRecord = (value) => !!value && typeof value === 'object' && !Array.isArray(value);
const safeDictionary = (value = {}) => Object.assign(Object.create(null), value);

// EAGER: only what the shell needs before the router dispatches. js/ui/shell/index.js
// reads exactly two keys: `ref().domains` and `services()` for the service
// drawer. Everything else belongs to a route and is loaded through `needs`.
//
// This used to list eleven files (275 KB, 13 requests), and `boot()` waited for
// every one before drawing anything. Under throttling, first content took 7.7 s
// even though the home page needs five of them and knowledge pages need none
// (docs/code-review.md §1/§3).
const FILES = {
  services:     'data/services.json',
  reference:    'data/reference-data.json',
};

// Deferred (H4): the router calls core.ensure(mod.needs) BEFORE rendering and
// remembers the promise per key (PENDING), so ten callers create one request.
// Failures enter the same FAILED register as startup files and appear in the
// error banner.
const DEFERRED = {
  applications: 'data/applications.json',           // Application catalogue + landing pages
  news:         'data/news.json',                   // Home page, #/news, search
  contacts:     'data/contacts.json',               // Service and application contacts
  documents:    'data/documents.json',              // Document archive, search
  projects:     'data/projects.json',               // Construction projects, My cases
  media:        'data/media.json',                  // 55 KB, media library ONLY
  catalogLabels:'data/catalog-labels.json',         // Data catalogue only
  datasets:     'data/datasets.json',               // 115 KB, data catalogue + search only
  // Golden Record: GeoJSON, normalised during loading (see loadDeferred).
  buildings:    'data/buildings.geojson',           // 66 KB, portfolio + 9 other apps
  parcels:      'data/parcels.geojson',             // 79 KB, portfolio + media library ONLY
  // Property-inventory detail registers (SAP RE-FX subtables, re-keyed by bbl_id):
  assets:           'data/assets.json',              // Equipment
  contracts:        'data/contracts.json',           // Contracts
  costs:            'data/costs.json',               // Costs
  areas:            'data/area-measurements.json',   // Areas / measurements
  buildingContacts: 'data/building-contacts.json',   // Property contacts (not service contacts)
  landcovers:       'data/landcovers.geojson',       // Land cover, parcel tab only
  // Tenant portal (#/app/tenancies): tenancies, floors and spaces. These three
  // datasets are self-contained: location, image and contacts live on the
  // tenancy; use and SIA category live on the space. Generated by
  // scripts/build-tenancy-data.mjs.
  tenancies:        'data/tenancies.json',
  floors:           'data/floors.json',
  spaces:           'data/spaces.json',
  // Workspace-management portal: only the domain overlay state for the
  // canonical property (project, plan revisions and equipment totals). Address,
  // image, coordinates, floors and spaces remain in their Golden Record
  // datasets and are not duplicated in this file.
  workspacePlanning:'data/workspace-planning.json',
  // The Multispace equipment standard as data rather than as prose. It is the
  // shared vocabulary of the whole Workspace suite — the Plan-Editor tags rooms
  // with module numbers and reports them per floor — so stating it once means the
  // numbers have a definition, and a new handbook edition is a data change. The
  // file carries the edition it encodes, and NO prices: the handbook marks them
  // confidential.
  multispaceModules:'data/multispace-modules.json',
  // Realised Multispace spaces, as examples. A record is an ausgebauter ORT — a floor, a
  // zone within one, or a single room — not a building; the building is only where the
  // place is. Images are references into `media`, so licence, photographer and source
  // stay with the asset rather than being copied per example.
  workspaceExamples:'data/workspace-examples.json',
  // Metadata catalogue (#/app/metadata-catalog): the two layers BELOW the DCAT
  // catalogue. `businessObjects` is technology-neutral (a business object with
  // attributes per data domain), while `dataTables` is the physical layer: a
  // table, layer or extract with fields. Attribute mappings connect them, and
  // `datasetId` on a table continues into data/datasets.json.
  //
  // Named dataTables, not systemTables (2026-08-12): a record does NOT have to
  // belong to a source system. A data product someone assembled for a purpose of
  // their own is the same thing to a reader looking for a field definition, and
  // the old name declared an ownership the model never required. `system` and
  // `schema` stay OPTIONAL on the record for exactly that case.
  businessObjects:  'data/business-objects.json',
  dataTables:       'data/data-tables.json',
  // Building process documentation (#/app/process-docs): property-management
  // processes (L1–L3 denormalised on the record, BPMN path per process under
  // assets/bpmn/). The app loads each diagram on its detail page.
  processes:        'data/processes.json',
  // BBL intranet shop (#/app/shop): product catalogue from the workspace-
  // management prototype. Images are mirrored under assets/images/shop/.
  shopProducts:     'data/shop-products.json',
  shopCategories:   'data/shop-categories.json',
  // Demo people. The prototype has no user directory, so this file plays that
  // role: it is what makes «a bookmark belongs to somebody» expressible at all.
  // Deferred, not eager — the shell renders the signed-in name from the session
  // (js/core/session.js), never from here; only personal surfaces need the file.
  users:            'data/users.json',
};
// A former data/data-products.json (DataService and Concept entries) was deleted
// in e9a0f67; the comment claiming it «remains in place» outlived the file. Its
// subject matter now lives in dataTables above.

// Keys whose files could not be loaded. Without this record, failure would look
// like a plausible zero (an empty list means «no entries»). The shell instead
// shows an error banner, while C.empty() distinguishes «empty» from
// «unavailable» (core.available()).
const FAILED = new Set();

// Domain label per data key for the shell's error banner.
const DATA_AREA_LABELS = {
  buildings: 'Liegenschaften', parcels: 'Grundstücke', projects: 'Bauprojekte', services: 'Dienstleistungen',
  applications: 'Anwendungen', documents: 'Dokumente', media: 'Mediathek',
  news: 'News', contacts: 'Kontakte', reference: 'Referenzdaten',
  datasets: 'Datenkatalog', catalogLabels: 'Katalog-Beschriftungen',
  assets: 'Ausstattung', contracts: 'Verträge', costs: 'Kosten', areas: 'Flächen',
  buildingContacts: 'Objektkontakte', landcovers: 'Bodenbedeckung',
  tenancies: 'Mietverhältnisse', floors: 'Geschosse', spaces: 'Räume',
  workspacePlanning: 'Workspace-Planungsstände',
  multispaceModules: 'Multispace-Module',
  workspaceExamples: 'Multispace-Beispiele',
  businessObjects: 'Geschäftsobjekte', dataTables: 'Datentabellen',
  processes: 'Prozesse', users: 'Benutzende',
  shopProducts: 'Shop-Produkte', shopCategories: 'Shop-Kategorien',
};

// Object files (key-value maps) versus lists; determines fallback and validation.
// `multispaceModules` is one document, not a collection of records: it carries the
// handbook edition it encodes alongside the module list, so the edition and the modules
// can never be read apart.
const OBJECT_FILES = new Set(['reference', 'catalogLabels', 'multispaceModules', 'workspaceExamples']);
const RECORD_IDS = {
  services: 'serviceId', applications: 'appId', news: 'id', contacts: 'contactId',
  documents: 'docId', projects: 'projectId', media: 'mediaId', datasets: 'id',
  assets: 'assetId', contracts: 'contractId', costs: 'costId', areas: 'areaMeasurementId',
  buildingContacts: 'contactId', tenancies: 'tenancyId', floors: 'floorId', spaces: 'spaceId',
  workspacePlanning: 'buildingId', businessObjects: 'objectId', dataTables: 'tableId',
  processes: 'processId', shopProducts: 'id', shopCategories: 'id',
};

// Buildings come from the SAP RE-FX Golden Record (data/buildings.geojson): the
// same source and bbl_id values as the property-portfolio dashboard, so map deep
// links (#/app/portfolio?id=<bbl_id>) open in the inventory. Raw SAP fields are
// normalised here into the compact building shape consumed by all views (list,
// detail, form pickers and relations).
const OWNERSHIP = (v) => v === 'Eigentum Bund' ? 'Im Eigentum' : v === 'Miete' ? 'Anmieter' : 'Sonderfall';
function normalizeBuilding(feature) {
  const raw = (feature && feature.properties) || {};
  const isDiplomatic = /Botschaft|Konsulat|Diplomat|Vertretung/i.test(`${raw['bbl_bez'] || ''} ${raw['bbl_port'] || ''}`);
  return {
    bbl_id: raw['bbl_id'], businessEntityId: raw['bbl_we'] || '', egid: raw['av_egid'] || '',
    name: raw['bbl_bez'] || raw['bbl_id'], portfolioCategory: raw['bbl_port'] || raw['bbl_gbda1'] || '—', buildingType: raw['bbl_gbda1'] || '',
    street: [raw['adr_str'], raw['adr_hsnr']].filter(Boolean).join(' ').trim(),
    zip: raw['adr_plz'] || '', city: raw['adr_ort'] || '', country: raw['adr_land'] || '', canton: raw['adr_reg'] || '',
    lat: raw['wgs84_lat'], lng: raw['wgs84_lon'],
    gf: raw['garea_gf'] || 0, ngf: raw['garea_ngf'] || 0, hnf: raw['garea_hnf'] || 0,
    totalFloors: raw['gastw'] || 0, buildYear: raw['bbl_bjahr'] || '',
    ownership: OWNERSHIP(raw['bbl_eigen']), preservationStrategy: raw['bbl_ostr'] || '', heritage: raw['bbl_arch'] === 'Ja',
    // Researched, sourced facts about the real buildings (see research/README.md).
    // Empty for properties without published information, in which case the row is omitted.
    architect: raw['bbl_architekt'] || '', occupants: raw['bbl_nutzer'] || '',
    renovationYear: raw['bbl_vjahr'] || '', kgsCategory: raw['kgs_kat'] || '', kgsNumber: raw['kgs_nr'] || null,
    sources: Array.isArray(raw['quellen']) ? raw['quellen'] : [],
    status: raw['bbl_stat'] || '',                       // Raw status values; see reference.buildingStatuses.
    classification: isDiplomatic ? 'VERTRAULICH' : 'INTERN', // Not in Golden Record; derived from portfolio type
    // `media` selects mediaId values from data/media.json (media library only).
    media: Array.isArray(raw['media']) ? raw['media'] : [],
    // Portfolio images come DIRECTLY from the curated raw `bilder` selection on
    // the object (GeoJSON); the first becomes the main image via linkMedia().
    images: Array.isArray(raw['bilder']) ? raw['bilder'] : [],
    photoSrc: '', photo: '', imageCredit: '', imageSource: '', color: 'var(--color-secondary-600)',
  };
}

// Parcels (parcels.geojson): polygon geometry linked to the building through
// the business-entity segment of bbl_id (1080/4840/01 ↔ 1080/4840/AF). Geometry
// is retained for map polygons and the detail mini-map.
function normalizeParcel(feature) {
  const raw = (feature && feature.properties) || {};
  return {
    bbl_id: raw['bbl_id'], businessEntityId: raw['bbl_we'] || '', name: raw['bbl_bez'] || raw['bbl_id'], plotNumber: raw['av_nr'] || '',
    street: [raw['adr_str'], raw['adr_hsnr']].filter(Boolean).join(' ').trim(),
    zip: raw['adr_plz'] || '', city: raw['adr_ort'] || '', country: raw['adr_land'] || '', canton: raw['adr_reg'] || '',
    municipality: raw['bfs_gem'] || raw['adr_ort'] || '', egrid: raw['av_egrid'] || '',
    gsf: raw['larea_gsf'] || 0, zone: raw['av_znut'] || raw['av_zbez'] || '', portfolio: raw['bbl_port'] || '—',
    ownership: OWNERSHIP(raw['bbl_eigen']), status: raw['bbl_stat'] || '',
    lat: raw['wgs84_lat'], lng: raw['wgs84_lon'], geom: (feature && feature.geometry) || null,
    images: Array.isArray(raw['bilder']) ? raw['bilder'] : [],
  };
}

// Land cover (AV): polygons per parcel linked through bbl_id (= parcel ID) or
// geb_id (= building ID), for the parcel's «Bodenbedeckung» tab.
function normalizeLandcover(feature) {
  const raw = (feature && feature.properties) || {};
  return {
    parcelId: raw['bbl_id'], buildingId: raw['geb_id'], type: raw['av_type'] || '—', area: raw['lc_area'] || 0,
    status: raw['av_stat'] || '', egid: raw['av_egid'] || '', egrid: raw['av_egrid'] || '',
    geom: (feature && feature.geometry) || null, lat: raw['wgs84_lat'], lng: raw['wgs84_lon'],
  };
}

function validateRecords(records, url, key) {
  const idField = RECORD_IDS[key];
  const invalid = records.findIndex((record) => !isRecord(record)
    || (idField && (record[idField] == null || String(record[idField]).trim() === '')));
  if (invalid >= 0) throw new Error(`invalid record ${invalid}: ${url}`);
  if (key === 'businessObjects') {
    const nested = records.findIndex((record) => !Array.isArray(record.attributes)
      || record.attributes.some((attribute) => !isRecord(attribute)
        || !Array.isArray(attribute.mappings)
        || attribute.mappings.some((mapping) => !isRecord(mapping))));
    if (nested >= 0) throw new Error(`invalid business-object structure ${nested}: ${url}`);
  }
  if (key === 'dataTables') {
    const nested = records.findIndex((record) => !Array.isArray(record.fields)
      || record.fields.some((field) => !isRecord(field)));
    if (nested >= 0) throw new Error(`invalid table structure ${nested}: ${url}`);
  }
  if (key === 'tenancies') {
    const nested = records.findIndex((record) => !Array.isArray(record.floors)
      || record.floors.some((floorId) => typeof floorId !== 'string'));
    if (nested >= 0) throw new Error(`invalid tenancy structure ${nested}: ${url}`);
  }
  if (key === 'workspacePlanning') {
    const nested = records.findIndex((record) => record.floors != null
      && (!Array.isArray(record.floors) || record.floors.some((floor) => !isRecord(floor))));
    if (nested >= 0) throw new Error(`invalid workspace structure ${nested}: ${url}`);
  }
  if (key === 'shopCategories') {
    const validCategory = (record) => isRecord(record)
      && record.id != null && String(record.id).trim() !== ''
      && Array.isArray(record.children) && record.children.every(validCategory);
    const nested = records.findIndex((record) => !validCategory(record));
    if (nested >= 0) throw new Error(`invalid shop category ${nested}: ${url}`);
  }
  return records;
}

function validateFeatureCollection(collection, url) {
  if (collection.type !== 'FeatureCollection' || !Array.isArray(collection.features)) {
    throw new Error(`expected a GeoJSON FeatureCollection: ${url}`);
  }
  const requiredProperty = 'bbl_id';
  const invalid = collection.features.findIndex((feature) => !isRecord(feature)
    || feature.type !== 'Feature'
    || !isRecord(feature.properties)
    || feature.properties[requiredProperty] == null
    || String(feature.properties[requiredProperty]).trim() === ''
    || (feature.geometry !== null && !isRecord(feature.geometry)));
  if (invalid >= 0) throw new Error(`invalid GeoJSON feature ${invalid}: ${url}`);
  return collection;
}

function fallbackFor(key) {
  return OBJECT_FILES.has(key) ? Object.create(null) : [];
}

function dispatchDataEvent(name, key) {
  try { window.dispatchEvent(new CustomEvent(name, { detail: { key } })); } catch { /* No DOM. */ }
}

async function load() {
  const entries = await Promise.all(Object.entries(FILES).map(async ([k, url]) => {
    const isObject = OBJECT_FILES.has(k);
    try {
      // Shape validation (C4) sends a file that parses but has the wrong root
      // shape (for example projects.json → {}) down the failure path instead of
      // throwing later in the first accessor (`{}.find`).
      let value = await fetchJSON(url, { shape: isObject ? 'object' : 'array' });
      if (!isObject) value = validateRecords(value, url, k);
      if (k === 'reference') value = safeDictionary(value);
      FAILED.delete(k);
      return [k, value];
    } catch (e) {
      console.warn('[core] could not load', url, e.message);
      FAILED.add(k);
      return [k, fallbackFor(k)];
    }
  }));
  for (const [k, v] of entries) DATA[k] = v;
  return DATA;
}

// Main image and attribution come DIRECTLY from the object's curated raw
// `bilder` selection (buildings.geojson / parcels.geojson); the first image is
// the main image. data/media.json is NO LONGER read for this purpose (the
// register belongs solely to the media library). Without `bilder`, the object
// remains image-free (a colour surface) instead of showing an Unsplash filler.
function linkMedia() {
  for (const object of [...(DATA.buildings || []), ...(DATA.parcels || [])]) {
    const firstImage = (object.images || [])[0];
    object.photoSrc = firstImage ? (firstImage.src || '') : '';
    object.photo = '';
    object.imageCredit = firstImage ? (firstImage.credit || '') : '';
    object.imageSource = firstImage ? (firstImage.sourceUrl || '') : '';
  }
}

// --- Loading deferred datasets (H4) -----------------------------------------
// ONE remembered promise per key means ten calls create one request and later
// callers await the same one. Failures enter the same register as startup
// failures so the error banner also shows deferred failures.
const PENDING = new Map();
const LOADED = new Set();

async function loadDeferred(key) {
  const url = DEFERRED[key];
  const isObject = OBJECT_FILES.has(key);
  try {
    // GeoJSON datasets carry {type,features} rather than a list and are
    // normalised during loading into the compact shape consumed by every view.
    const NORMALIZERS = { buildings: normalizeBuilding, parcels: normalizeParcel, landcovers: normalizeLandcover };
    const ID_FIELDS = { buildings: 'bbl_id', parcels: 'bbl_id', landcovers: 'parcelId' };
    if (NORMALIZERS[key]) {
      const featureCollection = validateFeatureCollection(await fetchJSON(url, { shape: 'object' }), url);
      DATA[key] = (featureCollection.features || []).map(NORMALIZERS[key]).filter((item) => item[ID_FIELDS[key]]);
      // Main image and attribution live on the objects. Relink after either
      // dataset because buildings and parcels can arrive independently.
      if (key === 'buildings' || key === 'parcels') linkMedia();
    } else {
      let value = await fetchJSON(url, { shape: isObject ? 'object' : 'array' });
      if (isObject) value = safeDictionary(value);
      else value = validateRecords(value, url, key);
      DATA[key] = value;
      // The reverse mapping index may have been built while the dataset was
      // still empty (two routes, two ensure calls), which would leave the table
      // view permanently showing an empty-realisation message.
      if (key === 'businessObjects') MAP_INDEX = null;
    }
    const recovered = FAILED.delete(key);
    LOADED.add(key);
    if (recovered) dispatchDataEvent('core:data-loaded', key);
    return true;
  } catch (e) {
    console.warn('[core] could not load', url, e.message);
    FAILED.add(key);
    LOADED.delete(key);
    DATA[key] = fallbackFor(key);
    // The error banner was rendered at startup and does not know about this
    // failure yet; without the event, it would remain invisible.
    dispatchDataEvent('core:data-failed', key);
    return false;
  }
}

// ensure('assets','costs') → Promise. Keys loaded at startup are skipped;
// unknown keys reject the promise so a route typo cannot look like a successful
// dataset load.
function ensure(...keys) {
  const requested = keys.flat();
  const unknown = requested.filter((key) => typeof key !== 'string'
    || (!hasOwn(DEFERRED, key) && !hasOwn(FILES, key)));
  if (unknown.length) {
    return Promise.reject(new Error(`Unknown data keys: ${unknown.map(String).join(', ')}`));
  }
  const list = [...new Set(requested.filter((key) => hasOwn(DEFERRED, key)))];
  return Promise.all(list.map((k) => {
    if (LOADED.has(k)) return true;
    if (!PENDING.has(k)) {
      const pending = loadDeferred(k).finally(() => PENDING.delete(k));
      PENDING.set(k, pending);
    }
    return PENDING.get(k);
  }));
}

const find = (arr, key, id) => (arr || []).find(x => x && x[key] === id);

// --- Metadata catalogue: reverse mapping direction -------------------------
// Mappings live ON THE ATTRIBUTE of a business object; that is their authoring
// direction («which field carries this concept?»). The table view needs the
// inverse question («which concept does this field realise?»). Instead of
// searching the entire dataset for each field, the index is built once per load;
// loadDeferred() discards it when fresh data arrives. Its key joins table and
// field names with «|», a character absent from both identifier alphabets
// (tables: a-z0-9-, fields: A-Za-z0-9_). A common separator would make
// «a.b»+«c» collide with «a»+«b.c».
let MAP_INDEX = null;
function mapIndex() {
  if (MAP_INDEX) return MAP_INDEX;
  MAP_INDEX = new Map();
  for (const o of DATA.businessObjects || []) {
    for (const a of Array.isArray(o?.attributes) ? o.attributes : []) {
      for (const m of Array.isArray(a?.mappings) ? a.mappings : []) {
        const k = `${m.tableId}|${m.field}`;
        if (!MAP_INDEX.has(k)) MAP_INDEX.set(k, []);
        MAP_INDEX.get(k).push({ objectId: o.objectId, objectName: o.name, attribute: a.name, match: m.match });
      }
    }
  }
  return MAP_INDEX;
}

export const core = {
  load,
  ensure,
  data: DATA,
  buildings: () => DATA.buildings || [],
  building: (id) => find(DATA.buildings, 'bbl_id', id),
  parcels: () => DATA.parcels || [],
  parcel: (id) => find(DATA.parcels, 'bbl_id', id),
  // Parcels for a building (or vice versa) through the business-entity segment of bbl_id.
  parcelsForBuilding: (bid) => { const we = String(bid || '').split('/')[1]; return (DATA.parcels || []).filter(p => String(p.bbl_id).split('/')[1] === we); },
  projects: () => DATA.projects || [],
  project: (id) => find(DATA.projects, 'projectId', id),
  // Property-inventory detail registers per building via buildingId (= bbl_id).
  assetsForBuilding: (bid) => (DATA.assets || []).filter(a => a.buildingId === bid),
  contractsForBuilding: (bid) => (DATA.contracts || []).filter(c => c.buildingId === bid),
  costsForBuilding: (bid) => (DATA.costs || []).filter(c => c.buildingId === bid),
  areasForBuilding: (bid) => (DATA.areas || []).filter(a => a.buildingId === bid),
  buildingContactsFor: (bid) => (DATA.buildingContacts || []).filter(c => c.buildingId === bid),
  // Land cover per parcel (parcelId = the parcel's bbl_id).
  landcoversForParcel: (pid) => (DATA.landcovers || []).filter(l => l.parcelId === pid),
  // Tenant portal. `floorsForTenancy` reads the floor list ON the tenancy (a
  // floor is rented, not the building), rather than every floor in the building.
  // Metadata catalogue. `realisedBy` answers the inverse mapping question
  // (field → concepts), while `realisationsOf` gathers every mapping for ONE
  // business object across its attributes. Both need only the index above, not
  // a third file.
  businessObjects: () => DATA.businessObjects || [],
  businessObject: (id) => find(DATA.businessObjects, 'objectId', id),
  dataTables: () => DATA.dataTables || [],
  dataTable: (id) => find(DATA.dataTables, 'tableId', id),
  // Building process documentation: flat list, detail lookup by processId.
  processes: () => DATA.processes || [],
  processDoc: (id) => find(DATA.processes, 'processId', id),
  // Die Ablaeufe des Portals stehen im selben Bestand, unterschieden durch
  // ihren Ast. Eine Quelle, zwei Sichten darauf.
  processDefinitions: () => (DATA.processes || []).filter((r) => r.branch === 'portal'),
  processDefinition: (id) => find(DATA.processes, 'processId', id),
  // The Multispace standard: one document carrying the edition and its modules, so the
  // two cannot be read apart. `multispaceModule` looks one up by its handbook number.
  multispaceModules: () => DATA.multispaceModules || Object.create(null),
  multispaceModule: (nr) => ((DATA.multispaceModules || {}).modules || [])
    .find((module) => Number(module.nr) === Number(nr)) || null,
  workspaceExamples: () => (DATA.workspaceExamples || {}).examples || [],
  workspaceExample: (slug) => ((DATA.workspaceExamples || {}).examples || [])
    .find((example) => example.slug === String(slug)) || null,
  shopProducts: () => DATA.shopProducts || [],
  shopProduct: (id) => find(DATA.shopProducts, 'id', Number(id)),
  shopCategories: () => DATA.shopCategories || [],
  dataDomains: () => (DATA.reference || {}).dataDomains || [],
  realisedBy: (tableId, field) => mapIndex().get(`${tableId}|${field}`) || [],
  realisationsOf: (o) => (Array.isArray(o?.attributes) ? o.attributes : [])
    .flatMap((a) => (Array.isArray(a?.mappings) ? a.mappings : [])
      .map((m) => ({ attribute: a.name, ...m }))),
  // Every mapping that points to ONE table, for the table detail page.
  realisationsForTable: (tableId) => {
    const out = [];
    for (const o of DATA.businessObjects || []) {
      for (const a of Array.isArray(o?.attributes) ? o.attributes : []) {
        for (const m of Array.isArray(a?.mappings) ? a.mappings : []) {
          if (m.tableId === tableId) out.push({ objectId: o.objectId, objectName: o.name, attribute: a.name, field: m.field, match: m.match });
        }
      }
    }
    return out;
  },
  tenancies: () => DATA.tenancies || [],
  tenancy: (id) => find(DATA.tenancies, 'tenancyId', id),
  floors: () => DATA.floors || [],
  floor: (id) => find(DATA.floors, 'floorId', id),
  floorsForBuilding: (bid) => (DATA.floors || []).filter((floor) => floor.buildingId === bid),
  spaces: () => DATA.spaces || [],
  floorsForTenancy: (t) => (t && t.floors ? t.floors : []).map((fid) => find(DATA.floors, 'floorId', fid)).filter(Boolean),
  spacesForFloor: (fid) => (DATA.spaces || []).filter((s) => s.floorId === fid),
  services: () => DATA.services || [],
  service: (id) => find(DATA.services, 'serviceId', id),
  applications: () => DATA.applications || [],
  application: (id) => find(DATA.applications, 'appId', id),
  documents: () => DATA.documents || [],
  documentsForBuilding: (bid) => (DATA.documents || []).filter(d => (d.linkedTo || []).includes(bid)),
  media: () => DATA.media || [],
  // The knowledge-and-resources area has NO dataset: standards, templates, instructions
  // and processes are static pages (js/pages/knowledge.js, regulations.js).
  // These are document directories for reading and downloading. A directive is
  // a document issued elsewhere, and the portal links to it instead of
  // cataloguing it (docs/sitemap.md §2.4).
  news: () => DATA.news || [],
  newsItem: (id) => find(DATA.news, 'id', id),
  // Demo people. `user` looks one up by the id the session carries.
  users: () => DATA.users || [],
  user: (id) => find(DATA.users, 'userId', id),
  contacts: () => DATA.contacts || [],
  ref: () => DATA.reference || {},
  // DCAT-AP-CH datasets (Datenbezug). Strings are multilingual objects; the
  // portal is DE-only, so read them through core.t().
  datasets: () => DATA.datasets || [],
  dataset: (id) => find(DATA.datasets, 'id', id),
  t: (v) => (v && typeof v === 'object') ? (v.de ?? v.en ?? '') : (v ?? ''),
  label: (key, fallback) => {
    const labels = DATA.catalogLabels;
    return labels && hasOwn(labels, key) ? labels[key] : (fallback || key);
  },
  // Data-failure state (P0-4): available() reports whether a key loaded, while
  // failedAreas() returns the domain labels of failed areas.
  available: (key) => !FAILED.has(key),
  failedAreas: () => Array.from(FAILED).map(k => hasOwn(DATA_AREA_LABELS, k) ? DATA_AREA_LABELS[k] : k),
};
