// Representative route and state matrix for the CD review. Dynamic collections
// use one stable detail record; stateful apps include views with a distinct
// layout or interaction model.
export const REVIEW_ROUTES = [
  { route: '/', slug: 'home' },
  { route: '/services', slug: 'services' },
  { route: '/services/stoerung-melden', slug: 'services_report-fault' },
  { route: '/applications', slug: 'applications' },
  { route: '/applications?area=buildings', slug: 'applications_area_buildings' },
  { route: '/applications/liegenschaften-inventar', slug: 'applications_property-inventory' },
  { route: '/applications/eshop', slug: 'applications_eshop' },
  { route: '/data', slug: 'data' },
  { route: '/data/catalog', slug: 'data_catalog' },
  { route: '/data/catalog/11', slug: 'data_catalog_detail' },
  { route: '/data/digitalisation', slug: 'data_digitalisation' },
  { route: '/data/digitalisation/strategy', slug: 'data_digitalisation_strategy' },
  { route: '/data/digitalisation/vision', slug: 'data_digitalisation_vision' },
  { route: '/data/digitalisation/principles', slug: 'data_digitalisation_principles' },
  { route: '/data/ict-projects', slug: 'data_ict-projects' },
  { route: '/knowledge', slug: 'knowledge' },
  { route: '/knowledge/it', slug: 'knowledge_it' },
  { route: '/knowledge/procurement', slug: 'knowledge_procurement' },
  { route: '/knowledge/accommodation', slug: 'knowledge_accommodation' },
  { route: '/knowledge/publishing', slug: 'knowledge_publishing' },
  { route: '/knowledge/guides', slug: 'knowledge_guides' },
  { route: '/knowledge/processes', slug: 'knowledge_processes' },
  { route: '/news', slug: 'news' },
  { route: '/news/N-01', slug: 'news_detail' },
  { route: '/my-cases', slug: 'my-cases' },
  { route: '/my-cases/seed-1', slug: 'my-cases_detail' },
  { route: '/search?q=bau', slug: 'search_q_construction' },
  { route: '/app/portfolio', slug: 'app_portfolio' },
  { route: '/app/portfolio?view=map', slug: 'app_portfolio_map', slow: true },
  { route: '/app/portfolio?id=1080%2F4840%2FAF', slug: 'app_portfolio_detail', slow: true },
  { route: '/app/media-library', slug: 'app_media-library' },
  { route: '/app/media-library?view=map', slug: 'app_media-library_map', slow: true },
  { route: '/app/media-library/MED-001', slug: 'app_media-library_detail' },
  { route: '/app/dataportal', slug: 'app_dataportal' },
  { route: '/app/dataportal/energie-klima', slug: 'app_dataportal_energy-climate', slow: true },
  { route: '/app/dataportal/immobilien?tab=entwicklung', slug: 'app_dataportal_real-estate', slow: true },
  { route: '/app/projects', slug: 'app_projects' },
  { route: '/app/projects/PRJ-01', slug: 'app_projects_detail' },
  { route: '/app/tenancies', slug: 'app_tenancies' },
  { route: '/app/tenancies/MV-2026-001', slug: 'app_tenancies_detail', slow: true },
  { route: '/app/tenancies/MV-2026-001?tab=grundriss&floor=1080-4850-AG-2og', slug: 'app_tenancies_floorplan', slow: true },
  { route: '/app/metadata-catalog', slug: 'app_metadata-catalog' },
  { route: '/app/metadata-catalog?id=gebaeude', slug: 'app_metadata-catalog_object' },
  { route: '/app/metadata-catalog?table=gis-immo-building', slug: 'app_metadata-catalog_table' },
  { route: '/app/process-docs', slug: 'app_process-docs' },
  { route: '/app/process-docs?id=TQ.21.00.00.01', slug: 'app_process-docs_detail' },
  { route: '/app/process-docs?id=TQ.21.00.00.01&tab=diagramm', slug: 'app_process-docs_diagram', slow: true },
  { route: '/app/shop', slug: 'app_shop' },
  { route: '/app/shop/product/3', slug: 'app_shop_product' },
  { route: '/app/shop/cart', slug: 'app_shop_cart' },
  { route: '/app/shop/checkout', slug: 'app_shop_checkout' },
  { route: '/app/document-archive', slug: 'app_document-archive' },
  { route: '/app/space-request', slug: 'app_space-request' },
  { route: '/app/fault-report', slug: 'app_fault-report' },
  { route: '/app/building-create', slug: 'app_building-create', slow: true },
  { route: '/app/workspace', slug: 'app_workspace' },
  { route: '/app/workspace?id=1080%2F6650%2FAA', slug: 'app_workspace_detail', slow: true },
  { route: '/app/workspace?id=1080%2F6650%2FAA&floor=1080-6650-AA-eg', slug: 'app_workspace_floorplan', slow: true },
  { route: '/app/workspace?id=1080%2F6210%2FAA&floor=1080-6210-AA-eg', slug: 'app_workspace_floorplan_legacy', slow: true },
  { route: '/app/floorplan-editor', slug: 'app_floorplan-editor_buildings', slow: true },
  { route: '/app/floorplan-editor?building=1080%2F6650%2FAA', slug: 'app_floorplan-editor_floors', slow: true },
  { route: '/app/floorplan-editor?building=1080%2F6650%2FAA&floor=1080-6650-AA-2og', slug: 'app_floorplan-editor', slow: true },
  { route: '/app/floorplan-editor?building=1080%2F6650%2FAA&floor=1080-6650-AA-2og&view=3d', slug: 'app_floorplan-editor_3d', slow: true },
  { route: '/app/floorplan-editor?building=1080%2F6650%2FAA&floor=1080-6650-AA-2og&view=walk', slug: 'app_floorplan-editor_walk', slow: true },
  { route: '/app/floorplan-editor?building=1080%2F6650%2FAA&floor=1080-6650-AA-2og&edit=1', slug: 'app_floorplan-editor_edit', slow: true },
  { route: '/app/floorplan-editor?building=1080%2F6650%2FAA&floor=1080-6650-AA-2og&selected=room%3A1080-6650-AA-2og-05&edit=1&library=modules', slug: 'app_floorplan-editor_room_edit', slow: true },
  { route: '/app/room-booking', slug: 'app_room-booking', slow: true },
  { route: '/app/transaction', slug: 'app_transaction' },
  { route: '/app/api-docs', slug: 'app_api-docs', slow: true },
];

export const REVIEW_VIEWPORTS = [320, 768, 1440];
